version: '3.8'
services:
  dev-db:
    image: postgres:17
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'waktu-solat'
    networks:
      - waktu-solat-network
networks:
  waktu-solat-network:
    driver: bridge
